### ISSUE TITLE
partition backup empty space

### ISSUE THREAD

**Issue by dim-geo** [YoRyan/sia-slice#1]
Hi,

Scenario: 100 mb used, partition size 1tb.

If I understand correctly, when you backup a partition it will backup the whole partition, even if empty space is not used at all, because sia-slice cannot detect that.
If the empty space is zero filled, the lz will minimize usage but still this remains an issue.

The only solution is using a loop device.
Any other solution?

**Comment by YoRyan** [comment]
Yes, you are correct. One solution would be to ignore blocks that contain nothing but zeroes. The caveat would be that this would still depend on the disk being zeroed out before use.

As things stand, I believe that if you upload a file smaller than 40MB, you do not actually have to upload any padded data, even if you pay for it.
